---
- debug: msg="##### SP INFLUXDB DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

- name: MONIT InfluxDB  - running Docker containers
  docker_container:
    name: son-monitor-influxdb
    image: sonatanfv/son-monitor-influxdb:{{ sp_ver }}
    state: started
    restart_policy: "always"
    network_mode: bridge
    networks:
    - name: "{{ docker_network_name }}"
      aliases:
        - son-monitor-influxdb
        - influxdb
        - influx
    published_ports: 8086:8086

