---

- debug: msg="##### VnV Lifecycle Manager Deployment {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

# Running the 5GTANGO VnV Lyfecycle Manager Deployment (Docker container)

- name: VnV LCM - running Docker containers
  docker_container:
    name: tng-vnv-lcm
    image: "{{ repository }}/tng-vnv-lcm:{{ version }}"
    env:
      APP_GK_BASE_URL: "{{ app_gk_base_url }}"
    log_driver: gelf
    log_options: gelf-address=udp://10.30.0.219:12900
    state: started
    recreate: yes
    pull: true
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - tng-vnv-lcm
    published_ports: "6100:6100"
    restart_policy: "always"
