---

- debug: msg="##### VnV Test Execution Engine Deployment {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

# Running the 5GTANGO VnV Test Execution Engine Deployment (Docker container)

- name: VnV TEE - running Docker containers
  docker_container:
    name: tng-vnv-tee
    image: "{{ repository }}/tng-vnv-tee:{{ version }}"
    env:
      APP_GK_BASE_URL: "{{ app_gk_base_url }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
      - "tee:/workspace"
    log_driver: gelf
    log_options: gelf-address=udp://10.30.0.219:12900
    state: started
    recreate: yes
    pull: true
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - tng-vnv-tee
    published_ports: "6200:6200"
    restart_policy: "always"
