---

- debug: msg="##### Installing python {{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

# Installing python dependencies

- name: Install dependencies
  apt: name={{ item }} state=present
  with_items:
    - software-properties-common
    - apt-transport-https
    - ca-certificates
    - curl
    
- name: Install Python 2.x
  raw: test -e /usr/bin/python || (apt update && apt install -y python-simplejson)
  register: test
  changed_when: test.stdout

- name: check to see if pip is already present
  command: "pip --version"
  ignore_errors: true
  register: pip_is_present
  changed_when: false

- block:
   - name: download get-pip.py
     get_url:
       url: https://bootstrap.pypa.io/get-pip.py
       dest: /tmp
       validate_certs: no
   - name: install pip
     command: "python /tmp/get-pip.py"
   - name: delete get-pip.py
     file: state=absent path=/tmp/get-pip.py

- name: Install docker-py python module
  pip:
    name: docker-py
    version: "1.9.0"

- name: Install cryptography python module
  pip:
    name: cryptography

- name: Install idna python module
  pip:
    name: idna
