---
# Running the Sonata GK BSS Docker Image
- debug: msg="##### SP BSS DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
- name: deploying GATEKEEPER BSS (as a Docker container)
  docker_container:
    name: son-bss
    image: "{{ repository }}/son-yo-gen-bss:{{ version }}"
    command: "grunt serve:integration --gkApiUrl=http://{{ target }}:32001/api/v2 --hostname=0.0.0.0 --userManagementEnabled=true --licenseManagementEnabled=true --debug"
    state: started
    recreate: yes
    pull: true
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-bss
    published_ports:
      - "25001:1337"
      - "25002:1338"
    restart_policy: "always"
