---
# Running the Sonata GK FUNCTIONS (Docker container)
- debug: msg="##### SP GTK-FUNCTIONs DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S') }}"
- name: GATEKEEPER FUNCTIONS - running Docker containers
  docker_container:
    name: son-gtkfnct
    image: "{{ repository }}/son-gtkfnct:{{ version }}"
    env:
      CATALOGUES_URL: http://son-catalogue-repos:4011/catalogues/api/v2
      RACK_ENV: integration
    state: started
    recreate: yes
    pull: true
    network_mode: bridge
    networks:
      - name: "{{ docker_netw_name }}"
        aliases:
          - son-gtkfnct
    published_ports: "5500:5500"
    restart_policy: "always"
