---
# Running the Sonata GK RECORDs (Docker container)
- debug: msg="##### SP GTK-RECORDs DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
- name: GATEKEEPER RECORDS - running Docker containers
  docker_container:
    name: son-gtkrec
    image: "{{ repository }}/son-gtkrec:{{ version }}"
    env:
      REPOSITORIES_URL: http://tng-rep:4012/records
      RACK_ENV: integration
    state: started
    recreate: yes
    pull: true
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-gtkrec
    published_ports: "5800:5800"
    restart_policy: "always"
