---

### Deploying databases

# deploy postgreSQL database engine
- import_tasks: pgsql.yml

# deploy MongoDB (NoSQL) database engine
- import_tasks: mongo.yml

# deploy Redis database engine
- import_tasks: redis.yml

# deploy postgreSQL database engine for monitoring
- import_tasks: pgsql-monitoring.yml

# deploy RabbitMQ message bus
- import_tasks: rabbitmq.yml

# deploy Influxdb
- import_tasks: influxdb.yml

### Deploying Gatekeeper components

# deploy Keycloak
- import_tasks: keycloak.yml

# deploy GUI
#- import_tasks: gui.yml

# deploy GUI
- import_tasks: portal.yml

# deploy BSS
- import_tasks: bss.yml

# deploy Gatekepper Validator module
- import_tasks: val.yml

# deploy Gatekepper Package module
- import_tasks: pkg.yml

# deploy Gatekepper Server module
- import_tasks: srv.yml

# deploy Gatekepper Function module
- import_tasks: fnct.yml

# deploy Gatekepper Records module
- import_tasks: gtkrec.yml

# deploy Gatekepper VIM module
- import_tasks: vim.yml

# deploy Gatekepper Lisense module
- import_tasks: lic.yml

# deploy Gatekepper KPIs module
- import_tasks: kpi.yml

# deploy Gatekepper User Management module
- import_tasks: usr.yml

# deploy Gatekepper Rate Limit module
- import_tasks: rlt.yml

# deploy Gatekepper API module
#- import_tasks: gtkapi.yml

# deploy Gatekepper API module
- import_tasks: api-gtw.yml

# deploy Repositories
- import_tasks: repos.yml

### Deploying Mano Components

# deploy PluginManager of MANO framework
- import_tasks: pluginmgr.yml

# deploy Service Lifecycle Manager of MANO framework
- import_tasks: slm.yml

# deploy Function Lifecycle Manager of MANO framework
- import_tasks: flm.yml

# deploy Specific Manager Registry of MANO framework
- import_tasks: smr.yml

# deploy Placement of MANO framework
- import_tasks: placement.yml

# deploy Placement Plugin of MANO framework
- import_tasks: placementplugin.yml

### Deploying Monitoring Components

# deploy Monitoring Pushgateway
- import_tasks: pushgw.yml

# deploy Monitoring Prometheus
- import_tasks: prometheus.yml

# deploy Monitoring Manager
- import_tasks: monitmgr.yml

# deploy Monitoring Probe
- import_tasks: probe.yml

# deploy Security Gateway
- import_tasks: sec-gtw.yml
