---
# Running the Sonata GK PACKAGES (Docker container)
- debug: msg="##### SP GTK-PACKAGEs DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S') }}"
- name: GATEKEEPER PACKAGES - running Docker containers
  docker_container:
    name: son-gtkpkg
    image: "{{ repository }}/son-gtkpkg:{{ tng_ver }}"
    env:
      CATALOGUES_URL: http://son-catalogue-repos:4011/catalogues/api/v2
      RACK_ENV: integration
    state: started
    recreate: yes
    pull: true
    network_mode: bridge
    networks:
      - name: "{{ docker_netw_name }}"
        aliases:
          - son-gtkpkg
    published_ports: "5100:5100"
    restart_policy: "always"
