---
# Running the MANO Plug-in Manager (Docker container)
- debug: msg="##### MANO Plug-in ManagerDEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
- name: MANO Plug-in Manager (Docker container)
  docker_container:
    name: pluginmanager
    image: "{{ repository }}/pluginmanager:{{ version }}"
    env:
      mongo_host: son-mongo
      broker_host: amqp://guest:guest@son-broker:5672/%2F
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - pluginmanager
        links:
          - son-broker
          - son-mongo
    restart_policy: "always"
    state: started
    recreate: yes
    pull: true
    published_ports: 8001:8001

- name: Wait until the string "Plugin manager" is UP
  wait_for: host=0.0.0.0 port=8001 timeout=30 delay=10 state=started

- pause:
    seconds: 10
