---
# Running the 5GTANGO Security Gateway (Docker container)
- debug: msg="##### 5GTANGO SEC-GTW DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
- name: run the 5GTANGO Security Gateway
  docker_container:
    name: "tng-sec-gtw"
    image: "{{ repository }}/tng-sec-gtw:{{ version }}"
    state: started
    pull: true
    restart_policy: "always"
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - tng-sec-gtw
    published_ports:
      - "80:80"
      - "443:443"
    volumes: 
      - "/etc/ssl/private/sonata/:/etc/nginx/cert/"

