---
# Running the 5GTANGO Slice Manager (Docker container)
- debug: msg="##### Service Platform TNG-SLICE-MNGR DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
- name: 5GTANGO Slice Manager (tng-slice-mngr) (Docker container)
  docker_container:
    name: tng-slice-mngr
    image: "{{ repository }}/tng-slice-mngr:{{ version }}"
    state: started
    recreate: yes
    pull: true
    restart_policy: "always"
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - tng-slice-mngr
    exposed_ports: 5998
    published_ports: "5998:5998"