---
# Running the Sonata SP  MANO Service Life-cycle Management (Docker container)
- debug: msg="##### SP  MANO Service Life-cycle Management DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S') }}"
- name: MANO Service Life-cycle Management (SLM) (Docker container)
  docker_container:
    name: servicelifecyclemanagement
    image: "{{ repository }}/servicelifecyclemanagement:{{ version }}"
    env:
      url_gk_api: "http://son-gtkapi:5000/api/v2/"
      url_nsr_repository: "http://son-catalogue-repos:4011/records/nsr/"
      url_vnfr_repository: "http://son-catalogue-repos:4011/records/vnfr/"
      url_monitoring_server: http://son-monitor-manager:8000/api/v1/
      broker_host: amqp://guest:guest@son-broker:5672/%2F
    network_mode: bridge
    networks:
      - name: "{{ docker_netw_name }}"
        aliases:
          - servicelifecyclemanagement
        links:
          - son-broker
    restart_policy: "always"
    state: started
    recreate: yes
    pull: true
