---
# Running the Sonata SP SPECIFIC MANAGER REGISTRY Docker Image
- debug: msg="##### SP SPECIFIC MANAGER REGISTRY DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S') }}"
- name: MANO Specific Manager Registry (SMR) (Docker container)
  docker_container:
    name: specificmanagerregistry
    image: "{{ repository }}/specificmanagerregistry:{{ version }}"
    env:
      broker_host: amqp://guest:guest@son-broker:5672/%2F
      broker_name: son-broker,broker
    network_mode: bridge
    networks:
      - name: "{{ docker_netw_name }}"
        aliases:
          - specificmanagerregistry
        links:
          - son-broker
    restart_policy: "always"
    state: started
    recreate: yes
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
