---
# Running the Sonata Infrastructure Abstractor VIM Adaptor (Docker container)
- debug: msg="##### SP Infrastructure Abstractor VIM Adaptor DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S') }}"
- name: deploying Infrastructure Abstractor VIM Adaptor (Docker container)
  docker_container:
    name: son-sp-infrabstract
    image: "{{ repository }}/son-sp-infrabstract:{{ version }}"
    restart_policy: "always"
    state: started
    recreate: yes
    pull: true
    env:
      broker_host: "son-broker"
      broker_uri: "amqp://guest:guest@son-broker:5672/%2F"
      repo_host: "son-postgres"
      repo_port: "5432"
      repo_user: "{{ ia_repo_user }}"
      repo_pass: "{{ ia_repo_pass }}"
      network_mode: bridge
    networks:
      - name: "{{ docker_netw_name }}"
        aliases:
          - son-sp-infrabstract

