nbofvms: 1
vm_user: ubuntu
image: xenial64
flavor: m1.small
os_security_groups: "{{ plat }}-secgrp"
fip: admin_floating_net
availability_zone: nova
region_name: RegionOne
key_name: son-install
int_net_id: "5788d300-92c1-4efa-8f4f-5b0830638c9f" # DEMO
ext_net_id: "83d48c16-8461-4939-9cb3-e7e240ec9538" # FIP

