---

#- yum: name=epel-release state=latest

#- name: install Docker dependency libraries
#  yum: name={{ item }} state=present update_cache=yes
#  with_items:
#  - python-pip

- include_tasks: "{{ lookup('env','PWD') }}/roles/python/tasks/{{ ansible_distribution_release }}.yml"

- name: make sure docker-python RPM is not installed
  yum: name=docker-python state=absent

- name: make sure required PyPi packages are installed
  pip:
    name: docker-py
    state: present

- name: add Docker repo to YUM
  copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo owner=root group=root mode=0644

- name: install Docker on CentOS7
  yum: name=docker-engine state=present update_cache=yes

- name: add Docker configuration options
  copy: src=docker2systemd dest=/etc/sysconfig/docker owner=root group=root mode=0644

- name: create a directory if it doesn't exist
  file: path=/etc/systemd/system/docker.service.d/ state=directory mode=0755

- name: "Configuring Docker Options"
  copy: src=docker.conf dest=/etc/systemd/system/docker.service.d/docker.conf owner=root group=root mode=0644
  register: result
#  notify:
#  - restart docker

#- shell: systemctl daemon-reload
#  when: result is changed

- name: restart service Docker-engine on CentOS, in all cases, also issue daemon-reload to pick up config changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- pause:
    seconds: 3

